# Generated by Django 3.0.5 on 2020-06-10 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_system', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='connection_type',
        ),
        migrations.RemoveField(
            model_name='device',
            name='title',
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='device',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='command_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
