# Generated by Django 3.0.5 on 2020-06-11 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_system', '0003_device_connection_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='command_history',
            field=models.TextField(default='{"0000-00-00": "New Device Added"}'),
        ),
    ]
