# Generated by Django 3.0.4 on 2020-06-13 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control_system', '0005_device_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='hostname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='device',
            name='uuid',
            field=models.TextField(blank=True, null=True),
        ),
    ]
