# Generated by Django 3.0.8 on 2020-07-03 00:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control_system', '0009_auto_20200702_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='command_history',
        ),
        migrations.CreateModel(
            name='CommandHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='control_system.Device')),
            ],
        ),
    ]
